### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by sweetchikoo2403** [DynamoYT/Ticket-Tool#1]
![image](https://user-images.githubusercontent.com/52192223/93322787-574d6f80-f831-11ea-8dc6-e7f2b9a3b5b4.png)
why dis coming
-Class 707 Productions#1332

**Comment by DynamoYT** [comment]
Try to reinstall node_modules or upgrade your nodejs to v14

**Comment by DynamoYT** [comment]
https://nodejs.org/en/
